- .travis.yml
- defaults/main.yml
- tasks/check_mandatory_vars.yml
- tasks/main.yml
- tests/test.yml
- vars/redhat.yml
Sets defaults for Postgres setup and provides user with ability to run Postgres either locally or remotely.
> Unopinionated PostgreSQL configuration

- defaults/main.yml
- tasks/configuration.yml
- tasks/main.yml
- templates/configuration.py.j2
- vars/main.yml
Please review the code and give me some suggestion to improve coding.
> Configure Netbox and perform deployment tasks

- tasks/deploy_netbox.yml
- tasks/install_via_git.yml
> Enforce install of DRF<3.7.0 for unsupported NetBox releases

- tasks/install_packages_apt.yml
check if ubuntu universe is available
> check universe repo for ubuntu server in install_packages_apt.yml

- tasks/main.yml
- tasks/variables.yml
- vars/debian-8.yml
- vars/debian-9.yml
- vars/redhat.yml
- vars/ubuntu-16.yml
- vars/ubuntu-18.yml
This allows users to specify/override the following parameters if needed:
- netbox_packages
- netbox_python_packages
- netbox_python_binary
- netbox_pip_binary
- netbox_ldap_packages
> Specify netbox packages

- .travis.yml
- README.md
- defaults/main.yml
- tasks/deploy_netbox.yml
- templates/configuration.py.j2
- tests/group_vars/netbox
This implements webhooks option and will install dependencies required during install
closes #37
> Implement webhooks support

- examples/playbook_single_host_webhooks_deploy.yml
- handlers/main.yml
- tasks/main.yml
- templates/netbox-rqworker.service.j2
- tests/test.yml
Adds the missing link for webhook integration....netbox-rqworker.service 
Adds example playbook for webhooks, just extends playbook_single_host_webhooks_deploy.yml
closes #37 
closes #39
> Added netbox-rqworker.service required by webhooks

- templates/configuration.py.j2
- templates/netbox-rqworker.service.j2
- templates/netbox.service.j2
- templates/netbox.socket.j2
- templates/pip_constraints.j2
- templates/uwsgi.ini.j2
Signed-off-by: Jean Wasilewski <jwasilewski@online.net>
> Fix ansible_managed headers to support multiline

- README.md
- defaults/main.yml
- tasks/install_packages_yum.yml
Fixes https://github.com/lae/ansible-role-netbox/issues/48
> Add var to skip epel install

- tasks/install_packages_yum.yml
I'm finding this is working for me on production system I was having issues with.
fixes #51
> Install psycopg2-binary on RHEL systems

- README.adoc
- defaults/main.yml
- templates/configuration.py.j2
Fixes https://github.com/lae/ansible-role-netbox/issues/64
This updates the configuration template and adds documentation for the new `netbox_database_extras` parameter.
> Add support for configuring database CONN_MAX_AGE

- README.adoc
- defaults/main.yml
Interim upstream version freeze for prepping final 0.8.x release.
> Freeze to version 2.6.12

- README.adoc
- defaults/main.yml
- templates/configuration.py.j2
- templates/netbox.service.j2
- templates/uwsgi.ini.j2
- tests/group_vars/netbox
- tests/test.yml
Fixes https://github.com/lae/ansible-role-netbox/issues/68
Adds configuration and templates for metrics configurations.
> Add support for Netbox metrics configurations

- .gitignore
- tasks/deploy_netbox.yml
- tasks/load_variables.yml
- tasks/validate_variables.yml
- vars/main.yml
> Remote file storage support

- tasks/deploy_netbox.yml
See https://github.com/netbox-community/netbox/issues/4119 for more information.
> Run manage.py clearsessions on deploy

- tasks/install_via_git.yml
- templates/configuration.py.j2
Fixes #86
Upstream change https://github.com/netbox-community/netbox/pull/4366
> Rename webhooks Redis connection to tasks

- templates/configuration.py.j2
Fixes https://github.com/lae/ansible-role-netbox/issues/101
> Remove kwarg for newer versions of prometheus client

- templates/configuration.py.j2
> Replace DEFAULT_TIMEOUT by RQ_DEFAULT_TIMEOUT

- README.adoc
- defaults/main.yml
- templates/configuration.py.j2
> Add support for database OPTIONS dictionary

- README.adoc
> add a hint for problematic uWSGI behaviour

- README.adoc
- defaults/main.yml
- templates/configuration.py.j2
* Add options in netbox config to use redis with sentinels
* Update README
> Be able to use redis sentinels

- tasks/deploy_netbox.yml
- tasks/install_via_git.yml
Fixes #153 
This is a new step that's present in v3.2.3 and above. This should help close the gap for v3+ support
> Add tasks & checks for clearcache command

- .gitignore
- README.adoc
- defaults/main.yml
- handlers/main.yml
- molecule/default/converge.yml
- molecule/default/tests/test_default.py
- tasks/deploy_netbox.yml
- tasks/install_via_git.yml
- tasks/load_variables.yml
- tasks/main.yml
- templates/netbox-rqworker.service.j2
- templates/netbox.service.j2
- tests/test.yml
- vars/debian-12.yml
- vars/main.yml
> release v1.0.5

- vars/main.yml
> NetBox 4.0.0 and higher requires Python 3.10 or higher

- vars/amazon-2023.yml
Added variable file that allows for installation on Amazon Linux 2023
> Adding Amazon Linux 2023 support

- tasks/deploy_netbox.yml
- tasks/install_via_git.yml
Fixes https://github.com/lae/ansible-role-netbox/issues/184
> add reindex command for 3.4.5+

- tasks/deploy_netbox.yml
- tasks/install_via_git.yml
- vars/amazon-2023.yml
- vars/main.yml
> release v1.0.7
