lae/ansible-role-netbox

README.md
defaults/main.yml
examples/netbox_config.yml
examples/playbook_single_host_deploy.yml
tasks/deploy_netbox.yml

Realised this directory was effectively being cleared out on every upgrade thanks to https://github.com/digitalocean/netbox/issues/1938.
If anyone using this role is using the reports feature, they'll need to copy all of their files into the shared directory after running the updated role:
cd /srv/netbox/releases/netbox-$VERSION/netbox/reports
mv * /srv/netbox/shared/reports/

Configure reports to be stored in a shared directory by default

---

templates/uwsgi.ini.j2

Map the static files correctly when netbox is served from a specific
BASE_PATH.

Support BASE_PATH setting in netbox

---

.travis.yml
README.md
defaults/main.yml
examples/netbox_config.yml
meta/main.yml
tasks/deploy_netbox.yml
tasks/install_packages_apt.yml
tasks/install_packages_yum.yml
tasks/install_via_git.yml
tasks/main.yml
tasks/validate_variables.yml
templates/configuration.py.j2
tests/group_vars/netbox
tests/group_vars/netbox-git
tests/group_vars/netbox-python2
tests/install.yml
tests/inventory
vars/centos-7.yml
vars/debian-8.yml
vars/debian-9.yml
vars/main.yml
vars/ubuntu-16.yml
vars/ubuntu-18.yml

This branch currently is not ready for production until NetBox 2.4 is released, and is intended to track changes upstream that might break deployment (there is a travis cronjob configured to test this branch daily).
You can use this branch to deploy the NetBox 2.4 branch as usual by installing it using `ansible-galaxy` like below.
```
ansible-galaxy install https://github.com/lae/ansible-role-netbox/archive/feature/netbox-2.4.tar.gz,v0.6.0-pre,lae.netbox --force
```
You must specify the following role variables to test the 2.4 branch:
```
netbox_git: true
netbox_git_version: develop-2.4
```
* Python 2 support is dropped from the role (still supported by NetBox 2.4 but will be dropped in 2.5 - I'd rather not keep Python 2 support around if no one is configuring a Python 2 deployment with …

NetBox 2.4 release preparation

---

tasks/main.yml
vars/centos-7.yml
vars/debian-8.yml
vars/debian-9.yml
vars/ubuntu-16.yml
vars/ubuntu-18.yml

Except on distros with an unsupported version (which instead gets Python 2 setuptools installed).
https://github.com/ansible/ansible/issues/9515 introduced a dependency on setuptools in the pip module for Ansible 2.7.

Run Ansible with Python 3 once installed

---

defaults/main.yml
tasks/deploy_netbox.yml
templates/pip_constraints.j2

Instead of using string replacements on requirements.txt, use pip constraints
to limit package versions. Also add a variable 'netbox_pip_constraints' to
allow constraints defined outside the role.
This also blacklists pynacl 1.3.0 due to the issues described at
https://github.com/pyca/pynacl/issues/479 causing build failures on many
environments that do not have 'make' involved due to missing wheel builds.

Use pip constraints

---

tasks/load_variables.yml

In check-mode, the register task for _path_exec isn't executed, which then fails the set_fact task after it.
Since these are safe to run in check-mode, i've added the check_mode:false flag.

Allow role to run successfully in --check mode

---

defaults/main.yml
tasks/deploy_netbox.yml

This change will allow the deployer to use a custom NAPALM package
list which will allow them to use community drivers for devices
that are not natively supported via NAPALM (such as RouterOS).

napalm: allow using custom package list

---

examples/netbox_ldap_config.py.j2

In case of multi line setup for ansible_managed, validate task for ldap config are broken and netbox cannot start.
This fix permit to insert comment for all line.

Improves Jinja2 syntax for multi-line case for ansible_managed

---

templates/configuration.py.j2
tests/group_vars/netbox

A configuration value can become deeply nested especially 
when dealing with `NAPALM_ARGS`.  In this scenario the 
approach to dump the configuration tree with `to_nice_json`
can lead to the creation of a configuration file that is not
valid Python anymore.  Store these values as strings in the
`configuration.py` file and load them with `json.loads`.

Support deeply nested configurations

---

defaults/main.yml
molecule/default/playbook.yml
templates/configuration.py.j2

Related to issue #72 
Adds option to enable SSL for Redis connection for Netbox release 2.6. This is mainly needed when using managed Redis service like AWS ElastiCache. Also added the path for SCRIPTS_ROOT to playbook.yml used by molecule to pass the local tests. The CI tests seem to fail because of incompatibility with Netbox release 2.7.

add ssl option for redis

---

README.adoc
defaults/main.yml
tasks/deploy_netbox.yml
tasks/main.yml
templates/configuration.py.j2

This adds the full modularity to the redis config by creating two sets of redis variables if you choose to use them. It also completely eliminates the webhooks variable and any references to it, since it is now a requirement for 2.7.

Support separate Redis connection config for cache database

---

README.adoc
defaults/main.yml
tasks/deploy_netbox.yml
tasks/validate_variables.yml
tests/group_vars/netbox
tests/reports/nothing.py
tests/scripts/nothing.py

This adds a `netbox_reports` role variable in similar function to `netbox_scripts` and adds validation for the module names (mainly so that they can be imported by NetBox correctly - although no syntax validation is done for the scripts themselves).
Closes #70.

Report uploads and some validation

---

.gitignore
README.adoc
defaults/main.yml
tasks/deploy_netbox.yml
tasks/load_variables.yml
tasks/main.yml
tasks/validate_variables.yml
templates/configuration.py.j2
vars/main.yml

In the same vein as #40, this branch will track upstream NetBox 2.7 development. Do not use this in production.
To deploy NetBox 2.7, use `ansible-galaxy` to install this branch:
```
ansible-galaxy install https://github.com/lae/ansible-role-netbox/archive/feature/netbox-2.7.tar.gz,v0.9.0-pre,lae.netbox --force
```
~~Using `netbox_stable` will use the latest beta (currently `2.7-beta1`), whilst using `netbox_git` will grab you the latest from the `develop-2.7` branch in NetBox.~~
For those wanting to test out 2.7, please report back here if you run into any issues that might be related to deployment (for anything that is a bug in NetBox itself, please [report it upstream](https://github.com/digitalocean/netbox/issues)).
If I'm missing anything, please leave a comment.
- ~~Requirement …

NetBox 2.7 release preparation

---

templates/configuration.py.j2

On some deployments it is desired to also have a password supplied
even when using a UNIX socket. Such deployments failed in the near past.
This commit implements a checks for such a condition and inserts the
setting if necessary.

chg: Added password setting for socket based db

---

tasks/load_variables.yml
tasks/main.yml

In the role's current format it sets `ansible_python_interpreter` to `netbox_python_binary` before executing any tasks, however it does not return it to the original value when the role completes. This can cause issues with subsequently executing modules such as yum, that require a python2 interpreter.
This can be resolved by the enduser by setting `ansible_python_interpreter` to the desired binary(assuming he knows it) after an `include_role` or `import_role` task before moving on to the next task/role but obviously this is not desirable. More importantly it does not solve for calling roles the old fashioned way such as this:
```
roles: 
- geerlingguy.postgresql
- davidwittman.redis
- lae.netbox
- nginxinc.nginx
```
Capturing the initial value of `ansible_python_interpreter` on load and …

Fix ansible_python_interpreter

---

README.adoc
defaults/main.yml
tasks/deploy_netbox.yml
tasks/load_variables.yml
tasks/main.yml
tests/group_vars/netbox

This introduces feature support for NetBox 2.8. If you can test this branch out by upgrading an existing installation (or copy of one), please do so and report back. Confirmations of successful upgrades will result in a quicker merge (as I'm having some test suite issues I need to resolve currently).
To deploy NetBox 2.8, use `ansible-galaxy` to install this branch:
```
ansible-galaxy install https://github.com/lae/ansible-role-netbox/archive/feature/netbox-2.8.tar.gz,v0.10.0-pre,lae.netbox --force
```
If I'm missing anything, please leave a comment.
- Requirement conditions for Python 3.6+ (complete)
- Plugins/additional Python dependencies support (complete)
Also, I'm considering marking this release as 1.0, since it has generally been stable for a while now. Thoughts?

NetBox 2.8 release

---

.travis.yml
tests/group_vars/netbox_stable_2_7
tests/inventory

Should fix most if not all of the build errors as of late.

Update test suite to travis-lxc 0.9.0, remove ansible devel

---

tasks/deploy_netbox.yml
tasks/generate_secret_key.yml
tasks/load_variables.yml
templates/configuration.py.j2
templates/uwsgi.ini.j2

This works around the problem in #66 that if you use the (increasingly more
common) include_role pattern variables you set externally could appear
immutable to the role logic. Thus, using set_fact with a combine() to
add SECRET_KEY to netbox_config will not work as expected.
Introducing a new 'private' (and thus mutable) variable in
load_variables works around the problem and allows the include_role
pattern to work.

Use 'private' variable for netbox_config (#66)

---

README.adoc
defaults/main.yml
examples/playbook_single_host_deploy.yml
tasks/install_via_git.yml
templates/configuration.py.j2

This introduces feature support for NetBox 2.9. If you can test this branch out by upgrading an existing installation (or copy of one), please do so and report back. Confirmations of successful upgrades will result in a quicker merge (as I'm having some test suite issues I need to resolve currently).
To deploy NetBox 2.9, use `ansible-galaxy` to install this branch:
```
ansible-galaxy install https://github.com/lae/ansible-role-netbox/archive/feature/netbox-2.9.tar.gz,v1.1.0-pre,lae.netbox --force
```
Not very many significant ones as far as I can tell. If I'm missing anything, please leave a comment.
* `RQ_DEFAULT_TIMEOUT` under redis config ([2.9.4 changelog](https://github.com/netbox-community/netbox/blob/develop/docs/release-notes/version-2.9.md#v294-2020-09-23))
Closes #112

NetBox 2.9 release

---

tasks/install_packages_yum.yml

The below deprecation warning comes at task 'Install psycopg2/selinux via pip on Red Hat-based distros':
'Invoking "pip" only once while using a loop via squash_actions is deprecated.'
Also there was a small problem when systemd units are being started: the daemon_reload was missing.

Fixed deprecation warning when installing multiple pip with "with_items"

---

tasks/deploy_netbox.yml

Looking at the upgrade.sh for Netbox 2.10 it needs to run manage.py trace_paths --no-input once to populate the new dcim_cablepath table, the manage.py migrate step doesn't do it.  In addition there are a couple of other commands in the update script to invalidate caches that probably make sense to run on updates.

Netbox 2.10 needs manage.py trace_paths run on upgrade

---

README.adoc
Vagrantfile
defaults/main.yml
examples/netbox_config.yml
tasks/deploy_netbox.yml
tasks/install_via_git.yml
templates/configuration.py.j2
tests/group_vars/netbox_git
tests/install.yml
tests/inventory
tests/vagrant/group_vars/all
tests/vagrant/package_role.yml
tests/vagrant/provision.yml
tests/vagrant/templates/detect-http-proxy.j2

This introduces feature support for NetBox 2.10.
* `INSECURE_SKIP_TLS_VERIFY` under redis config ([2.10.9 changelog](https://github.com/netbox-community/netbox/releases/tag/v2.10.9))
* trace_paths management command ([2.10.0 changelog](https://github.com/netbox-community/netbox/releases/tag/v2.10.0))
* Vagrant playbook updates since CI isn't working for now

NetBox 2.10 release

---

README.adoc
meta/main.yml
vars/debian-11.yml

This pull requests adds the neccessary variables file for running the role on Debian 11 ("bullseye") machines. The only change, in comparison to Debian 10, is the version of the Python interpreter.

Debian 11 support

---

defaults/main.yml
handlers/main.yml
tasks/deploy_netbox.yml
tasks/install_via_git.yml
tasks/main.yml
vars/main.yml

Fix #132 
Add tasks to support installation of Netbox 3.0:
* Use latest pip/setuptools in virtualenv => create first the virtualenv with latest pip/setuptools before installing other dependencies
* Change permissions on netbox home => when installing pip libraries the `{{ netbox_home }}/.cache` will be used so `{{ netbox_home }}` need to be owned by netbox user
* Update for Netbox **3.0** => some tasks has been marked only for netbox <= 3.0 / include https://github.com/lae/ansible-role-netbox/pull/139
* Setup housekeeping (https://github.com/lae/ansible-role-netbox/pull/134)
Some ideas/information were retrieved from:
* https://github.com/lae/ansible-role-netbox/pull/136
* https://github.com/lae/ansible-role-netbox/issues/132

Netbox 3.0 release

---

README.adoc
meta/main.yml
vars/ubuntu-22.yml

Only tested by running playbook on an updated Ubuntu 22.04 system, but I have a hard time seeing how this could break any older Ubuntu version.

Add support for Ubuntu 22.04

---

README.adoc
defaults/main.yml
tasks/main.yml

Some use cases might not be able to access the default `postgres` database. To make sure that this playbook also works in these scenarios, `maintenance_db` should be changed by using variables, passed from outside of the role.
The default should still remain on `postgres`:
https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_db_module.html

Add `netbox_database_maintenance` variable

---

.gitignore
README.adoc
defaults/main.yml
handlers/main.yml
molecule/default/converge.yml
molecule/default/tests/test_default.py
tasks/deploy_netbox.yml
tasks/main.yml
templates/netbox-rqworker.service.j2
tests/test.yml

This closes issue #129 
I oriented myself based on the [netbox-rq.service](https://github.com/netbox-community/netbox/blob/develop/contrib/netbox-rq.service) of the main netbox project.
I removed the reload of the rqworker and used a restart instead, as the service file from netbox does not have a reload.
Default install stayed at 1 process.
- Allow use of multiple rqworkers
- Add tests for changed rqworker processes

Allow use of multiple rqworkers

---

README.adoc
defaults/main.yml
tasks/load_variables.yml
tasks/main.yml
templates/netbox.service.j2
vars/main.yml

Fixes #144 
Also added a new version constraint for NetBox v3.2 requiring Python 3.8

Allow optional install of uwsgi into Netbox venv, and v3.2 version constraint

---

tasks/main.yml
vars/debian-12.yml

Based on @davidmehren's [PR #162](https://github.com/lae/ansible-role-netbox/pull/162), but implementing @lae's [suggestion](https://github.com/lae/ansible-role-netbox/pull/162#issuecomment-1750519004) to install uWSGI in a venv instead of using `--break-system-packages`.

Compatibility with Debian 12, venv-based

---

tasks/main.yml
vars/debian-12.yml

The newer Python on Debian 12 requires the use of the `--break-system-packages` pip flag to install packages globally.
Debian 12 also does not ship with a cron implementation anymore, so the `systemd-cron` compatibility package needs to be installed.

Compatibility with Debian 12

---

tasks/install_via_git.yml

This avoids "fatal: detected dubious ownership in repository" errors that cause all feature-detection commands to fail.
Fixes #164

Run "git log" under the same user that cloned the repo

---

tasks/deploy_netbox.yml
tasks/install_via_git.yml

https://github.com/netbox-community/netbox/commit/2d1f88272497ca72d2e1eca8e291c04538c6810e removed the 'clearcache' command, so this needs to be skipped for release 3.7.0 and later.

Compatibility with Netbox 3.7

---

README.adoc
tasks/main.yml

Role (probably, I didn't check) fails to run if community collections aren't installed, so specify that it's needed for this role (though it's also needed for any postgres installation roles in the first place).
In response to:
> Guy may I suggest to add to the readme as prequisite to make this role work ? (for those who use ansible-core)
> 
> ```shell
> ansible-galaxy collection install community.postgresql   
> ```
_Originally posted by @MozeBaltyk in https://github.com/lae/ansible-role-netbox/issues/132#issuecomment-1961040712_

Clarify community.postgresql usage in docs

---

tasks/deploy_netbox.yml

Added a task to modify the version of a pip package already present in the netbox requirements. For example, with netbox v3.4.10, there are issues due to the rq package requiring downgrading to version 1.13.0 or installing django-rq v2.10.1 instead of the 2.7.0 set in the requirement.

Add task to overwrite package dependencies

---

vars/main.yml

This is the recommended way to reference the user model according to the documentation[1].  It should be supported by at least Django 4, so can be assumed to work for NetBox releases older than 4.0 as well.  I have only tested it with 4.0(.1) though.
[1] https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#referencing-the-user-model
Closes #179

User get_user_model() rather than importing User directly
